name: Azure Container Apps Deploy

on:
  push:
    branches:
      - dev
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code check out
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: splittedcontainerregistry
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: splitted-frontend
          containerAppEnvironment: splitted-environment
          resourceGroup: splittedresources
          imageToBuild: splittedcontainerregistry.azurecr.io/splitted-frontend:${{ github.sha }}
          dockerfilePath: Dockerfile
